export const ORDER_PUBLICATION_SUCCESS = 'ORDER_PUBLICATION_SUCCESS';
export const ORDER_ALL_PUBLICATIONS_SUCCESS = 'ORDER_ALL_PUBLICATIONS_SUCCESS';
export const ORDER_CATEGORY_PUBLICATIONS_SUCCESS = 'ORDER_CATEGORY_PUBLICATIONS_SUCCESS';
export const ORDER_PUBLICATION_REQUEST = 'ORDER_PUBLICATION_REQUEST';
export const ORDER_PUBLICATION_ERROR = 'ORDER_PUBLICATION_ERROR';

export const ORDER_NEW_CATEGORY_SUCCESS = 'ORDER_NEW_CATEGORY_SUCCESS';
export const ORDER_NEW_CATEGORY_ERROR = 'ORDER_NEW_CATEGORY_ERROR';